name: Build Static Screen

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential autoconf automake libtool pkg-config \
                              libncurses-dev libutempter-dev libpam0g-dev libcrypt-dev \
                              wget file curl musl musl-tools

      - name: Get Latest Screen Version
        run: |
          SCREEN_VERSION=$(curl -s https://ftp.gnu.org/gnu/screen/ | grep -oP 'screen-\K[0-9.]+(?=\.tar\.gz)' | sort -V | tail -n1)
          echo "SCREEN_VERSION=$SCREEN_VERSION" >> $GITHUB_ENV

      - name: Download and Compile `screen`
        run: |
          wget "http://ftp.gnu.org/gnu/screen/screen-${{ env.SCREEN_VERSION }}.tar.gz"
          tar -xzf "screen-${{ env.SCREEN_VERSION }}.tar.gz"
          cd "screen-${{ env.SCREEN_VERSION }}"

          CC=musl-gcc ./configure CFLAGS="-O2 -static -D_FORTIFY_SOURCE=0" \
              LDFLAGS="-static" --disable-shared --without-pam --without-utempter

          make -j$(nproc)
          strip src/screen || strip screen

          mv src/screen ../screen-static || mv screen ../screen-static
          file ../screen-static | grep "statically linked" || (echo "Build failed: Binary is not static!" && exit 1)

      - name: Upload Binary
        uses: actions/upload-artifact@v4
        with:
          name: screen-static
          path: screen-static
          retention-days: 30

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "v${{ env.SCREEN_VERSION }}"
          release_name: "Screen v${{ env.SCREEN_VERSION }} (Fully Static Build)"
          body: |
            ## GNU Screen v${{ env.SCREEN_VERSION }}
            - **Fully static build** (compiled with `musl`)
            - **No `glibc` dependencies** (compatible with ESXi)
            - Built with `LDFLAGS="-static"` and `musl-gcc`

            ### 🛠 Installation:
            ```
            wget -O /bin/screen https://github.com/YOUR_USERNAME/static-screen/releases/latest/download/screen-static
            chmod +x /bin/screen
            ```
            Run `screen --version` to verify installation.
            
            🚀 Built automatically via GitHub Actions.
          draft: false
          prerelease: false
          files: screen-static
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
