name: Build Static Screen

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential autoconf automake libtool pkg-config \
                              musl musl-tools musl-dev musl-utils wget file curl \
                              ncurses-bin libncurses6 libtinfo6 binutils libc-dev

      - name: Get Latest Screen Version
        run: |
          SCREEN_VERSION=$(curl -s https://ftp.gnu.org/gnu/screen/ | sed -n 's/.*screen-\([0-9.]\+\)\.tar\.gz.*/\1/p' | sort -V | tail -n1)
          if [ -z "$SCREEN_VERSION" ]; then
            echo "Error: Could not determine latest screen version."
            exit 1
          fi
          echo "SCREEN_VERSION=$SCREEN_VERSION" >> $GITHUB_ENV

      - name: Download and Compile `screen`
        run: |
          DOWNLOAD_URL="https://ftp.gnu.org/gnu/screen/screen-${{ env.SCREEN_VERSION }}.tar.gz"

          echo "Downloading $DOWNLOAD_URL..."
          wget -O screen.tar.gz "$DOWNLOAD_URL" || { echo "Download failed!"; exit 1; }
          tar -xzf screen.tar.gz
          cd "screen-${{ env.SCREEN_VERSION }}"

          export CC=/usr/bin/musl-gcc
          export PATH="/usr/bin:$PATH"

          ./configure --host=x86_64-linux-musl --enable-static \
                      CFLAGS="-O2 -static -D_FORTIFY_SOURCE=0" \
                      LDFLAGS="-static -lncurses -ltinfo"

          make -j$(nproc)
          strip src/screen || strip screen

          mv src/screen ../screen-static || mv screen ../screen-static
          file ../screen-static | grep "statically linked" || (echo "Build failed: Binary is not static!" && exit 1)

      - name: Upload Binary
        uses: actions/upload-artifact@v4
        with:
          name: screen-static
          path: screen-static
          retention-days: 30

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "v${{ env.SCREEN_VERSION }}"
          release_name: "Screen v${{ env.SCREEN_VERSION }} (Fully Static Build)"
          body: |
            ## GNU Screen v${{ env.SCREEN_VERSION }}
            - **Fully static build** (compiled with `musl`)
            - **No `glibc` dependencies** (compatible with ESXi)
            - Built with `LDFLAGS="-static"` and `musl-gcc`

            ### 🛠 Installation:
            ```
            wget -O /bin/screen https://github.com/YOUR_USERNAME/static-screen/releases/latest/download/screen-static
            chmod +x /bin/screen
            ```
            Run `screen --version` to verify installation.
            
            🚀 Built automatically via GitHub Actions.
          draft: false
          prerelease: false
          files: screen-static
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
